Repository usdoj-crt/beta-ada, pull requests merged in 2023-07, with the labels that each got.

#638 ballot box accessibility build along with pdf for download
  _assets/images/project-images/Picture1.jpg
  _assets/images/project-images/Picture2.jpg
  _assets/images/project-images/Picture3.jpg
  _pages/_resources/ballot-box-accessibility.md
  _pdfs/ballot-box-accessiblity.pdf
Labels: netlify-cms/pending_publish

#655 Cms/topics/criminal justice
  _assets/images/landing/criminal-justice.jpg
  _pages/_topics/criminal-justice.md
Labels: netlify-cms/pending_review

#661 removed dates
  _pages/_topics/child-care-centers.md
  _pages/_topics/community-integration.md
  _pages/_topics/emergency-planning.md
  _pages/_topics/opioid-use-disorder.md
  _pages/_topics/parental-rights.md
  _pages/_topics/telehealth.md
  _pages/_topics/voting.md
Labels: netlify-cms/draft

#658 Update Topics “criminal-justice”
  _pages/_topics/criminal-justice.md
Labels: netlify-cms/pending_publish
